




services:
  ecommerceapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: nest-docker
    container_name: ecommerceapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "3000" 
    # working_dir: /var/www/pokedex
    env_file:
      - .env.prod
      
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: postgres:15.3
    container_name: postgres-db
    restart: always
    env_file:
      - .env.prod
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    ports:
      - 5432:5432